# Nome da sua aplicação
service: winelog

# Nome da imagem no Docker Hub
image: mateusmed31415/winelog

proxy:
  app_port: 80

# Servidor VPS da Oracle Cloud (Vinhedo)
servers:
  web:
    - 157.151.28.170
  

# Onde as imagens do contêiner serão guardadas
registry:
  server: index.docker.io
  username: mateusmed31415
  password:
    - KAMAL_REGISTRY_PASSWORD

# Injeção de variáveis de ambiente de produção
env:
  clear:
    RAILS_ENV: production
    RAILS_LOG_TO_STDOUT: true
    SOLID_QUEUE_IN_PUMA: true
    RAILS_PORT: 3000
  secret:
    - RAILS_MASTER_KEY
    - ADMIN_EMAIL
    - DB_ADAPTER
    - DB_HOST
    - DB_PORT
    - DB_USER
    - DB_PASSWORD
    - DB_NAME
# Volumes persistentes para uploads locais do Active Storage
volumes:
  - "winelog_storage:/rails/storage"

# Caminho dos assets (CSS e JS) compilados pelo Propshaft
asset_path: /rails/public/assets

# Usuário padrão das instâncias Ubuntu na Oracle Cloud
ssh:
  user: ubuntu

# Configuração essencial para os processadores Ampere (ARM64) da OCI
builder:
  arch: arm64

# Atalhos úteis (Ex: kamal console)
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f

accessories:
  db:
    image: container-registry.oracle.com/database/free:latest
    roles:
      - web
    env:
      clear:
        ORACLE_SID: FREE
      secret:
        - ORACLE_PASSWORD
    volumes:
      - "winelog_db_data:/opt/oracle/oradata"
    port: "1521:1521"