# Name of your application. Used to uniquely configure containers.
service: winelog

# Name of the container image.
image: mateusmed31415/winelog

# Deploy to these servers.
servers:
  web:
    - 193.123.125.247
proxy:
  app_port: 80

# Where you keep your container images.
registry:
  server: index.docker.io
  username: mateusmed31415
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers
env:
  clear:
    SOLID_QUEUE_IN_PUMA: true
    DB_HOST: "winelog-db"
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
accessories:
  db:
    image: postgres:16
    host: 193.123.125.247
    port: "5432:5432"
    env:
      clear:
        POSTGRES_DB: winelog_production
        POSTGRES_USER: winelog
      secret:
        - POSTGRES_PASSWORD
    directories:
      - winelog_postgres_data:/var/lib/postgresql/data

# Use a persistent storage volume
volumes:
  - "winelog_storage:/rails/storage"

# Bridge fingerprinted assets, like JS and CSS, between versions.
asset_path: /rails/public/assets

# Use a different ssh user than root
ssh:
  user: ubuntu

# Configure the image builder.
builder:
  arch: amd64

# Aliases are triggered with "bin/kamal <alias>".
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"